import { FormEvent, useEffect, useState } from 'react'
import { Activity, CheckCircle2, Clock3, Coffee, HeartPulse, LineChart, Moon, Pill, Salad, AlertCircle, MessageCircle, BookHeart } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { askSugarPath, confirmMedicine, deleteMemory, getActivities, getDashboard, getGlucose, getMeals, getMedicines, getSleep, getMemories, logMeal } from './services/api'
import type { Dashboard } from './types/dashboard'
import type { ActivityEvent, AssistantReply, GlucoseReading, Meal, Medicine, SleepEvent, Memory } from './types/health'
import './index.css'

type Page = 'home' | 'glucose' | 'medicine' | 'meals' | 'activity' | 'sleep' | 'ask' | 'memory'
const time = (value: string) => new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })
const pages: Page[] = ['home', 'glucose', 'medicine', 'meals', 'activity', 'sleep', 'ask', 'memory']

export default function App() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [page, setPage] = useState<Page>('home'); const [error, setError] = useState(false)
  useEffect(() => { getDashboard().then(setDashboard).catch(() => setError(true)) }, [])
  if (error) return <main className="state"><AlertCircle size={34}/><h1>Sugar Path is temporarily unavailable.</h1><p>Please check that the local service is running.</p></main>
  if (!dashboard) return <main className="state"><HeartPulse className="pulse" size={38}/><p>Getting your day ready…</p></main>
  return <main className="app-shell"><header><div className="brand"><HeartPulse/><span>Sugar Path</span></div><span className="demo">Demo data only</span></header><nav aria-label="Sugar Path navigation">{pages.map(item => <button className={page === item ? 'active' : ''} onClick={() => setPage(item)} key={item}>{icon(item)}{item === 'ask' ? 'Ask' : item === 'memory' ? 'Memory' : item[0].toUpperCase() + item.slice(1)}</button>)}</nav>{page === 'home' ? <Home data={dashboard}/> : page === 'ask' ? <AskSugarPath/> : page === 'memory' ? <MemoryPage/> : <PhaseTwo page={page} refresh={() => getDashboard().then(setDashboard)}/>}<p className="disclaimer">Sugar Path is a prototype for organization and information only. It does not provide medical diagnosis, emergency care, or medicine dosing advice.</p></main>
}

function icon(page: Page) { return page === 'glucose' ? <LineChart/> : page === 'medicine' ? <Pill/> : page === 'meals' ? <Salad/> : page === 'activity' ? <Activity/> : page === 'sleep' ? <Moon/> : page === 'ask' ? <MessageCircle/> : page === 'memory' ? <BookHeart/> : <HeartPulse/> }
function Home({ data }: { data: Dashboard }) { return <><section className="intro"><p>{data.greeting}</p><h1>Your daily diabetes companion</h1></section><section className="glucose-panel"><div><span className="eyebrow">TODAY'S GLUCOSE</span><strong>{data.glucose.value_mg_dl} <small>mg/dL</small></strong><p><Activity size={18}/> Glucose {data.glucose.trend.toLowerCase()}</p></div><span className="updated">Updated {time(data.glucose.updated_at)}</span></section><section className="section"><h2>Medicine</h2>{data.medicines.map(m => <div className="row" key={m.label}><Pill/><div><strong>{m.label}</strong><span>{m.detail}</span></div>{m.status === 'taken' ? <CheckCircle2 className="success"/> : <Clock3 className="due"/>}</div>)}</section><section className="two-up"><article><Activity/><span>Today's activity</span><strong>{data.activity.duration_minutes} min walk</strong><small>{data.activity.steps?.toLocaleString()} steps</small></article><article><Salad/><span>Last meal</span><strong>{data.last_meal.meal_type}</strong><small>{data.last_meal.carbs_g} g carbohydrates</small></article></section><section className="meal"><Coffee/><div><span>Last meal</span><strong>{data.last_meal.description}</strong><small>{time(data.last_meal.timestamp)}</small></div></section></> }

function PhaseTwo({ page, refresh }: { page: Exclude<Page, 'home'>; refresh: () => void }) {
  const [glucose, setGlucose] = useState<GlucoseReading[]>([]); const [medicines, setMedicines] = useState<Medicine[]>([]); const [meals, setMeals] = useState<Meal[]>([]); const [activities, setActivities] = useState<ActivityEvent[]>([]); const [sleep, setSleep] = useState<SleepEvent[]>([]); const [notice, setNotice] = useState('')
  useEffect(() => { const load = async () => { try { if (page === 'glucose') setGlucose(await getGlucose()); if (page === 'medicine') setMedicines(await getMedicines()); if (page === 'meals') setMeals(await getMeals()); if (page === 'activity') setActivities(await getActivities()); if (page === 'sleep') setSleep(await getSleep()) } catch (e) { setNotice(e instanceof Error ? e.message : 'Unable to load information.') } }; load() }, [page])
  if (page === 'glucose') return <section className="page"><h1>Glucose</h1><p>Today’s simulated readings arrive at five-minute intervals.</p><div className="chart"><ResponsiveContainer width="100%" height={250}><AreaChart data={glucose}><XAxis dataKey="timestamp" tickFormatter={time} minTickGap={50}/><YAxis width={35}/><Tooltip labelFormatter={v => time(String(v))} formatter={v => [`${v ?? '—'} mg/dL`, 'Glucose']}/><Area type="monotone" dataKey="value_mg_dl" stroke="#0d6b6d" strokeWidth={3} fill="#cfe9e3"/></AreaChart></ResponsiveContainer></div><small>Mock CGM data only; it is not clinically validated.</small></section>
  if (page === 'medicine') return <section className="page"><h1>Medicine</h1><p>Confirm a dose only after you have taken it.</p>{medicines.map(m => <div className="row" key={`${m.id}-${m.time_of_day}`}><Pill/><div><strong>{m.time_of_day}: {m.name} {m.dose}</strong><span>{m.status === 'taken' && m.event_time ? `Taken ${time(m.event_time)}` : `${m.instructions} · ${m.status}`}</span></div>{m.status === 'taken' ? <CheckCircle2 className="success"/> : <button className="small-button" onClick={() => confirmMedicine(m.id, m.time_of_day).then(() => getMedicines()).then(setMedicines).then(refresh).then(() => setNotice('Medicine marked as taken.')).catch(e => setNotice(e.message))}>Mark taken</button>}</div>)}<Notice text={notice}/></section>
  if (page === 'meals') return <Meals meals={meals} setMeals={setMeals} notice={notice} setNotice={setNotice}/>
  const rows = page === 'activity' ? activities.map(a => [`${a.duration_minutes} minute ${a.activity_type}`, `${new Date(a.timestamp).toLocaleDateString()} · ${a.steps?.toLocaleString()} steps`]) : sleep.map(s => [`${Math.floor(s.duration_minutes / 60)}h ${s.duration_minutes % 60}m sleep`, `${new Date(s.end_time).toLocaleDateString()} · ${s.quality ?? 'Not recorded'}`])
  return <section className="page"><h1>{page === 'activity' ? 'Activity' : 'Sleep'}</h1><p>Your recent {page} from the synthetic demo data.</p>{rows.map(([heading, detail], index) => <div className="row" key={`${heading}-${index}`}>{page === 'activity' ? <Activity/> : <Moon/>}<div><strong>{heading}</strong><span>{detail}</span></div></div>)}</section>
}

function Meals({ meals, setMeals, notice, setNotice }: { meals: Meal[]; setMeals: (items: Meal[]) => void; notice: string; setNotice: (text: string) => void }) { const [description, setDescription] = useState(''); const [type, setType] = useState('meal'); const submit = (event: FormEvent) => { event.preventDefault(); logMeal(description, type).then(meal => { setMeals([meal, ...meals]); setDescription(''); setNotice('Meal added using the local food dataset.') }).catch(e => setNotice(e.message)) }; return <section className="page"><h1>Meals</h1><p>Log a meal in everyday language. Estimates use the local food list.</p><form className="meal-form" onSubmit={submit}><label>What did you eat?<input value={description} onChange={e => setDescription(e.target.value)} placeholder="2 rotis, dal and an egg" required/></label><label>Meal type<select value={type} onChange={e => setType(e.target.value)}><option value="meal">Meal</option><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option><option value="snack">Snack</option></select></label><button className="small-button">Add meal</button></form><Notice text={notice}/>{meals.map(m => <div className="row" key={m.id}><Coffee/><div><strong>{m.description}</strong><span>{m.estimated_carbs_g} g carbohydrates · {time(m.timestamp)}</span></div></div>)}</section> }
function Notice({ text }: { text: string }) { return text ? <p className="notice">{text}</p> : null }
function MemoryPage() { const [memories, setMemories] = useState<Memory[]>([]); const [notice, setNotice] = useState(''); useEffect(() => { getMemories().then(setMemories).catch(() => setNotice('Unable to load memories.')) }, []); const labels: Record<Memory['memory_type'], string> = { routine: 'Routine', preference: 'Preference', patient_fact: 'About you', system_observation: 'Observed pattern' }; const sources: Record<Memory['source'], string> = { user_explicit: 'You asked Sugar Path to remember this.', user_confirmed: 'You confirmed Sugar Path could remember this.', system_observation: 'Observed from your Sugar Path data.' }; const remove = (memory: Memory) => { if (!window.confirm('Remove this memory?')) return; deleteMemory(memory.id).then(() => { setMemories(memories.filter(item => item.id !== memory.id)); setNotice('Memory removed. Sugar Path will no longer use it.') }).catch(() => setNotice('Unable to remove this memory.')) }; return <section className="page"><h1>What Sugar Path remembers</h1><p>These are the useful routines, preferences, and facts you chose to save. This is not a copy of your conversations.</p><Notice text={notice}/>{memories.length === 0 && <div className="empty-memory">Nothing has been saved yet. You can say “Remember that…” in Ask Sugar Path.</div>}{memories.map(memory => <article className="memory-card" key={memory.id}><div><span className="memory-label">{labels[memory.memory_type]}</span><strong>{memory.content}</strong><small>{sources[memory.source]} · Updated {new Date(memory.updated_at).toLocaleDateString()}</small></div><button className="remove-button" onClick={() => remove(memory)}>Remove</button></article>)}</section> }
function AskSugarPath() { const [message, setMessage] = useState(''); const [reply, setReply] = useState<AssistantReply | null>(null); const [waiting, setWaiting] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); setWaiting(true); setReply(null); askSugarPath(message).then(setReply).catch(() => setReply({ message: "Sugar Path's AI assistant is temporarily unavailable.", sources_used: [], status: 'unavailable' })).finally(() => setWaiting(false)) }; return <section className="page"><h1>Ask Sugar Path</h1><p>Ask about your stored demo health information.</p><form className="meal-form" onSubmit={submit}><label>Your question<input value={message} onChange={e => setMessage(e.target.value)} placeholder="Did I take my morning medicine?" required/></label><button className="small-button" disabled={waiting}>{waiting ? 'Checking your information…' : 'Ask Sugar Path'}</button></form>{reply && <article className="answer"><strong>Sugar Path</strong><p>{reply.message}</p>{reply.sources_used.length > 0 && <details><summary>Data used for this answer</summary><ul>{reply.sources_used.map(source => <li key={source}>{source}</li>)}</ul></details>}</article>}<p className="helper">Sugar Path may check your glucose, meals, medicine, activity, or sleep history before answering.</p></section> }
