import { FormEvent, useEffect, useState } from 'react'
import { Activity, AlertCircle, Bell, CheckCircle2, ChevronRight, Clock3, Coffee, HeartPulse, LineChart, Moon, Pill, Printer, Salad, Sparkles } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { AppShell, PageHeader, type Page } from './components/AppShell'
import { askSugarPath, confirmMedicine, deleteMemory, dismissNotification, evaluateEvents, generateWeeklyReport, getActivities, getCurrentWeeklyReport, getDashboard, getGlucose, getMeals, getMedicines, getSleep, getMemories, getNotifications, logMeal, setNotificationRead } from './services/api'
import type { Dashboard } from './types/dashboard'
import type { ActivityEvent, AssistantReply, GlucoseReading, Meal, Medicine, SleepEvent, Memory, WeeklyReport, Notification } from './types/health'
import './index.css'

const time = (value: string) => new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })
const dateTime = (value: string) => new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })

export default function App() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [page, setPage] = useState<Page>('home'); const [error, setError] = useState(false); const [unread, setUnread] = useState(0)
  const refreshDashboard = () => getDashboard().then(setDashboard).catch(() => setError(true))
  const refreshNotifications = () => getNotifications().then(items => setUnread(items.filter(item => item.status === 'unread').length)).catch(() => undefined)
  useEffect(() => { refreshDashboard(); refreshNotifications() }, [])
  if (error) return <State title="We couldn't load Sugar Path" text="Please check that the local service is running, then try again." icon={<AlertCircle/>}/>
  if (!dashboard) return <State title="Getting your day ready" text="Loading your Sugar Path information…" icon={<HeartPulse className="pulse"/>}/>
  return <AppShell page={page} setPage={setPage} unread={unread}>{page === 'home' ? <Home data={dashboard} openPage={setPage}/> : page === 'ask' ? <AskSugarPath/> : page === 'memory' ? <MemoryPage/> : page === 'report' ? <WeeklyReportPage/> : page === 'notifications' ? <NotificationsPage openPage={setPage} refreshUnread={refreshNotifications}/> : <HealthPage page={page} refresh={refreshDashboard}/>}<footer className="disclaimer">Sugar Path is a prototype for organization and information only. It does not provide diagnosis, emergency care, or medicine dosing advice.</footer></AppShell>
}

function State({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <main className="state">{icon}<h1>{title}</h1><p>{text}</p></main> }
function Home({ data, openPage }: { data: Dashboard; openPage: (page: Page) => void }) { return <><section className="welcome"><p>{data.greeting}</p><h1>Your day, at a glance</h1><span className="demo inline-demo">Demo data only</span></section><section className="glucose-hero"><div><span className="eyebrow">CURRENT GLUCOSE</span><strong>{data.glucose.value_mg_dl}<small>mg/dL</small></strong><p><Activity aria-hidden="true"/> {data.glucose.trend} trend</p></div><small>Updated {time(data.glucose.updated_at)}</small></section><section className="dashboard-section"><div className="section-heading"><h2>Medicine today</h2><button onClick={() => openPage('medicine')}>View medicine <ChevronRight aria-hidden="true"/></button></div>{data.medicines.map(item => <article className="status-row" key={item.label}><Pill aria-hidden="true"/><div><strong>{item.label}</strong><span>{item.detail}</span></div>{item.status === 'taken' ? <span className="status success"><CheckCircle2 aria-hidden="true"/> Taken</span> : <span className="status attention"><Clock3 aria-hidden="true"/> Due</span>}</article>)}</section><section className="summary-grid"><article><Activity aria-hidden="true"/><span>Today’s activity</span><strong>{data.activity.duration_minutes} min walk</strong><small>{data.activity.steps?.toLocaleString()} steps</small></article><article><Salad aria-hidden="true"/><span>Latest meal</span><strong>{data.last_meal.meal_type}</strong><small>{data.last_meal.carbs_g} g estimated carbs</small></article></section><section className="latest-meal"><Coffee aria-hidden="true"/><div><span>Latest meal · {time(data.last_meal.timestamp)}</span><strong>{data.last_meal.description}</strong></div></section><button className="ask-cta" onClick={() => openPage('ask')}><Sparkles aria-hidden="true"/><span><strong>Ask Sugar Path</strong><small>Get help understanding your day</small></span><ChevronRight aria-hidden="true"/></button></> }

function HealthPage({ page, refresh }: { page: Extract<Page, 'glucose' | 'medicine' | 'meals' | 'activity' | 'sleep'>; refresh: () => void }) { const [glucose, setGlucose] = useState<GlucoseReading[]>([]); const [medicines, setMedicines] = useState<Medicine[]>([]); const [meals, setMeals] = useState<Meal[]>([]); const [activities, setActivities] = useState<ActivityEvent[]>([]); const [sleep, setSleep] = useState<SleepEvent[]>([]); const [notice, setNotice] = useState(''); const [hours, setHours] = useState(24)
  useEffect(() => { setNotice(''); const load = async () => { try { if (page === 'glucose') setGlucose(await getGlucose(hours)); if (page === 'medicine') setMedicines(await getMedicines()); if (page === 'meals') setMeals(await getMeals()); if (page === 'activity') setActivities(await getActivities()); if (page === 'sleep') setSleep(await getSleep()) } catch { setNotice('We couldn’t load this information. Please try again.') } }; load() }, [page, hours])
  if (page === 'glucose') { const latest = glucose[glucose.length - 1]; return <section><PageHeader title="Glucose" subtitle="Your recent synthetic demo readings."/><div className="period-control" aria-label="Glucose time period">{[[24, '24 hours'], [72, '3 days'], [168, '7 days']].map(([value, label]) => <button key={value} className={hours === value ? 'selected' : ''} onClick={() => setHours(value as number)}>{label}</button>)}</div><div className="chart-card"><div className="chart-summary"><strong>{latest?.value_mg_dl ?? '—'} <small>mg/dL</small></strong><span>{latest?.trend ?? 'Loading trend'}</span></div><ResponsiveContainer width="100%" height={260}><AreaChart data={glucose}><XAxis dataKey="timestamp" tickFormatter={time} minTickGap={46}/><YAxis width={34}/><Tooltip labelFormatter={value => time(String(value))} formatter={value => [`${value ?? '—'} mg/dL`, 'Glucose']}/><Area type="monotone" dataKey="value_mg_dl" stroke="var(--accent)" strokeWidth={3} fill="var(--accent-soft)"/></AreaChart></ResponsiveContainer></div><p className="page-note">Demo data only. These readings are not clinically validated.</p><Notice text={notice}/></section> }
  if (page === 'medicine') return <section><PageHeader title="Medicine" subtitle="Confirm a dose only after you have taken it."/>{medicines.map(item => <article className="medicine-card" key={`${item.id}-${item.time_of_day}`}><div className="medicine-icon"><Pill aria-hidden="true"/></div><div><span className="eyebrow">{item.time_of_day}</span><h2>{item.name} {item.dose}</h2><p>{item.status === 'taken' && item.event_time ? `Taken at ${time(item.event_time)}` : item.instructions}</p><span className={`status ${item.status === 'taken' ? 'success' : 'attention'}`}>{item.status === 'taken' ? <CheckCircle2 aria-hidden="true"/> : <Clock3 aria-hidden="true"/>}{item.status === 'taken' ? 'Taken' : 'Not logged yet'}</span></div>{item.status !== 'taken' && <button className="primary-button" onClick={() => confirmMedicine(item.id, item.time_of_day).then(() => getMedicines()).then(setMedicines).then(refresh).then(() => setNotice('Medicine marked as taken.')).catch(error => setNotice(error.message))}>Mark taken</button>}</article>)}<Notice text={notice}/></section>
  if (page === 'meals') return <Meals meals={meals} setMeals={setMeals} notice={notice} setNotice={setNotice}/>
  const activityPage = page === 'activity'; const rows = activityPage ? activities.map(item => ({ title: `${item.duration_minutes} minute ${item.activity_type}`, detail: `${new Date(item.timestamp).toLocaleDateString()} · ${item.steps?.toLocaleString() ?? 'No'} steps` })) : sleep.map(item => ({ title: `${Math.floor(item.duration_minutes / 60)}h ${item.duration_minutes % 60}m sleep`, detail: `${new Date(item.end_time).toLocaleDateString()} · ${item.quality ?? 'Quality not recorded'}` }))
  return <section><PageHeader title={activityPage ? 'Activity' : 'Sleep'} subtitle={activityPage ? 'How active you have been recently.' : 'Your recent sleep, shown without medical interpretation.'}/>{rows.length === 0 ? <Empty text={activityPage ? 'No activity has been recorded yet.' : 'No sleep has been recorded yet.'}/> : rows.map((row, index) => <article className="history-row" key={`${row.title}-${index}`}>{activityPage ? <Activity aria-hidden="true"/> : <Moon aria-hidden="true"/>}<div><strong>{row.title}</strong><span>{row.detail}</span></div></article>)}</section> }
function Meals({ meals, setMeals, notice, setNotice }: { meals: Meal[]; setMeals: (items: Meal[]) => void; notice: string; setNotice: (text: string) => void }) { const [description, setDescription] = useState(''); const [type, setType] = useState('meal'); const submit = (event: FormEvent) => { event.preventDefault(); logMeal(description, type).then(meal => { setMeals([meal, ...meals]); setDescription(''); setNotice('Meal added using the local demo food dataset.') }).catch(error => setNotice(error.message)) }; return <section><PageHeader title="Meals" subtitle="Log a meal in everyday language. Nutrition values are estimates."/><form className="meal-form" onSubmit={submit}><label>What did you eat?<input value={description} onChange={event => setDescription(event.target.value)} placeholder="e.g. 2 rotis, dal and an egg" required/></label><label>Meal type<select value={type} onChange={event => setType(event.target.value)}><option value="meal">Meal</option><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option><option value="snack">Snack</option></select></label><button className="primary-button">Add meal</button></form><Notice text={notice}/>{meals.length === 0 ? <Empty text="No meals logged yet. Add one above when you’re ready."/> : meals.map(item => <article className="history-row" key={item.id}><Coffee aria-hidden="true"/><div><strong>{item.description}</strong><span>{item.meal_type} · {item.estimated_carbs_g} g estimated carbs · {time(item.timestamp)}</span></div></article>)}</section> }
function AskSugarPath() { const [message, setMessage] = useState(''); const [reply, setReply] = useState<AssistantReply | null>(null); const [waiting, setWaiting] = useState(false); const suggestions = ['Why did my glucose rise this morning?', 'Did I take my morning medicine?', 'How was my week?', 'What do you remember about me?', 'Do I have anything I need to check?']; const submit = (event: FormEvent) => { event.preventDefault(); setWaiting(true); setReply(null); askSugarPath(message).then(setReply).catch(() => setReply({ message: "Sugar Path's AI assistant is temporarily unavailable.", sources_used: [], status: 'unavailable' })).finally(() => setWaiting(false)) }; return <section><PageHeader title="Ask Sugar Path" subtitle="Ask about your glucose, medicine, meals, activity, sleep, or weekly summary."/><form className="ask-form" onSubmit={submit}><label>Your question<textarea value={message} onChange={event => setMessage(event.target.value)} placeholder="What would you like to know?" required/></label><button className="primary-button" disabled={waiting}>{waiting ? 'Checking your information…' : 'Ask Sugar Path'}</button></form>{waiting && <div className="waiting"><Sparkles aria-hidden="true"/><div><strong>Sugar Path is checking your information.</strong><p>Local AI can take a little while on this device. You can still use other pages while it works.</p></div></div>}<div className="suggestions" aria-label="Suggested questions">{suggestions.map(question => <button key={question} onClick={() => setMessage(question)}>{question}</button>)}</div>{reply && <article className="answer"><strong>Sugar Path</strong><p>{reply.message}</p>{reply.sources_used.length > 0 && <details><summary>Data used for this answer</summary><ul>{reply.sources_used.map(source => <li key={source}>{source}</li>)}</ul></details>}</article>}</section> }
function MemoryPage() { const [items, setItems] = useState<Memory[]>([]); const [notice, setNotice] = useState(''); useEffect(() => { getMemories().then(setItems).catch(() => setNotice('We couldn’t load your memories.')) }, []); const labels: Record<Memory['memory_type'], string> = { routine: 'Routine', preference: 'Preference', patient_fact: 'About you', system_observation: 'Observed pattern' }; const sources: Record<Memory['source'], string> = { user_explicit: 'You asked Sugar Path to remember this.', user_confirmed: 'You confirmed Sugar Path could remember this.', system_observation: 'Observed from your Sugar Path data.' }; const remove = (memory: Memory) => { if (!window.confirm('Remove this memory? Sugar Path will no longer use it.')) return; deleteMemory(memory.id).then(() => { setItems(items.filter(item => item.id !== memory.id)); setNotice('Memory removed.') }).catch(() => setNotice('We couldn’t remove this memory.')) }; return <section><PageHeader title="What Sugar Path remembers" subtitle="Useful information you chose to save, never a copy of your conversations."/><Notice text={notice}/>{items.length === 0 ? <Empty text="Sugar Path isn’t remembering anything yet. You can say “Remember that…” in Ask Sugar Path."/> : items.map(item => <article className="memory-card" key={item.id}><div><span className="eyebrow">{labels[item.memory_type]}</span><strong>{item.content}</strong><small>{sources[item.source]} · Updated {new Date(item.updated_at).toLocaleDateString()}</small></div><button className="secondary-button" onClick={() => remove(item)}>Remove</button></article>)}</section> }
function WeeklyReportPage() { const [report, setReport] = useState<WeeklyReport | null>(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(''); useEffect(() => { getCurrentWeeklyReport().then(setReport).catch(() => setNotice('We couldn’t load your weekly summary.')).finally(() => setLoading(false)) }, []); const generate = () => { setLoading(true); generateWeeklyReport().then(setReport).catch(() => setNotice('We couldn’t generate the report.')).finally(() => setLoading(false)) }; if (loading && !report) return <section><PageHeader title="Weekly Report" subtitle="Preparing your weekly summary…"/><Loading/></section>; if (!report) return <section><PageHeader title="Weekly Report" subtitle="A calm summary of your week."/><Notice text={notice}/><button className="primary-button" onClick={generate}>Generate weekly report</button></section>; const s = report.summary; const duration = (minutes: number | null) => minutes === null ? 'Not recorded' : `${Math.floor(minutes / 60)}h ${minutes % 60}m`; return <section className="report-page"><div className="report-heading"><div><span className="demo inline-demo">Demo data only</span><h1>Sugar Path Weekly Summary</h1><p>{new Date(`${s.week_start}T00:00:00`).toLocaleDateString()} to {new Date(`${s.week_end}T00:00:00`).toLocaleDateString()}</p></div><div className="report-actions"><button className="secondary-button" onClick={generate} disabled={loading}>{loading ? 'Refreshing…' : 'Refresh'}</button><button className="secondary-button" onClick={() => window.print()}><Printer aria-hidden="true"/> Print / Save as PDF</button></div></div><div className="report-grid"><ReportCard title="Glucose" value={`Average ${s.glucose.average_mg_dl ?? '—'} mg/dL`} detail={`${s.glucose.reading_count} readings`}/><ReportCard title="Medicine" value={`${s.medicine.taken_doses} taken`} detail={`${s.medicine.adherence_percent ?? '—'}% adherence`}/><ReportCard title="Meals" value={`${s.meals.logged_meals} meals`} detail={`${s.meals.average_carbs_g ?? '—'} g estimated carbs`}/><ReportCard title="Activity" value={`${s.activity.total_minutes} minutes`} detail={`${s.activity.active_days} active days`}/><ReportCard title="Sleep" value={duration(s.sleep.average_duration_minutes)} detail={`${s.sleep.nights_recorded} nights recorded`}/></div><section className="report-section"><h2>Patterns noticed</h2>{s.patterns.length ? s.patterns.map(item => <p key={item.description}>{item.description} <small>({item.matching_days} of {item.observed_days} days)</small></p>) : <p>No consistent pattern was found this week.</p>}</section><section className="report-section"><h2>Questions for your clinician</h2><ul>{s.questions_for_clinician.map(item => <li key={item}>{item}</li>)}</ul></section><p className="report-note">This summary uses synthetic demo data. It does not diagnose conditions or recommend medicine changes.</p></section> }
function ReportCard({ title, value, detail }: { title: string; value: string; detail: string }) { return <article className="report-card"><span>{title}</span><strong>{value}</strong><small>{detail}</small></article> }
function NotificationsPage({ openPage, refreshUnread }: { openPage: (page: Page) => void; refreshUnread: () => void }) { const [items, setItems] = useState<Notification[]>([]); const [notice, setNotice] = useState(''); const load = () => getNotifications().then(setItems).catch(() => setNotice('We couldn’t load notifications.')); useEffect(() => { void load() }, []); const update = (id: number, action: 'read' | 'dismiss') => (action === 'read' ? setNotificationRead(id) : dismissNotification(id)).then(updated => { setItems(items.map(item => item.id === id ? updated : item)); refreshUnread() }).catch(() => setNotice('We couldn’t update this notification.')); const evaluate = () => evaluateEvents().then(result => { setNotice(result.notifications_created ? `${result.notifications_created} new notification${result.notifications_created === 1 ? '' : 's'} found.` : 'You’re all caught up.'); load(); refreshUnread() }).catch(() => setNotice('We couldn’t check for notifications.')); const target = (category: string): Page => category === 'weekly_report_ready' ? 'report' : category === 'glucose_event' ? 'glucose' : 'medicine'; const visible = items.filter(item => item.status !== 'dismissed'); return <section><PageHeader title="Notifications" subtitle="Helpful updates from your Sugar Path data." action={<button className="secondary-button" onClick={evaluate}>Check now</button>}/><Notice text={notice}/>{visible.length === 0 ? <Empty text="You’re all caught up."/> : visible.map(item => <article className={`notification-card ${item.status}`} key={item.id}><Bell aria-hidden="true"/><div><span className="eyebrow">{item.category === 'medicine_due' || item.category === 'medicine_missed' ? 'Medicine' : item.category === 'weekly_report_ready' ? 'Weekly summary' : item.category === 'glucose_event' ? 'Glucose' : 'Reminder'}</span><strong>{item.message}</strong><small>{dateTime(item.created_at)} · {item.status === 'unread' ? 'New' : 'Read'}</small><div className="notification-actions"><button onClick={() => openPage(target(item.category))}>View</button>{item.status === 'unread' && <button onClick={() => update(item.id, 'read')}>Mark read</button>}<button onClick={() => update(item.id, 'dismiss')}>Dismiss</button></div></div></article>)}</section> }
function Notice({ text }: { text: string }) { return text ? <p className="notice" role="status">{text}</p> : null }
function Empty({ text }: { text: string }) { return <div className="empty-state"><Sparkles aria-hidden="true"/><p>{text}</p></div> }
function Loading() { return <div className="loading"><HeartPulse className="pulse" aria-hidden="true"/> Loading…</div> }
